### ISSUE TITLE
Support for TYPO3 7.6 and TYPO3 8?

### ISSUE THREAD

**Issue by sypets** [undkonsorten/powermailpdf#3]
Generell question: Are there plans to support TYPO3 7, TYPO3 8 and higher versions of powermail? Is anyone working on this already? 

We are currently using this Extension with TYPO3 7.6. It generelly works well. Since powermail 4.0.1 and higher there is a problem with double-opt in. I could possibly supply an error report and a pull request.

It would actually be ideal if the functionality could be merged into powermail ...

**Comment by Starkmann** [comment]
Hi,
yes there is a plan on doing this. Till right now there was no need for us to do it. But it will come when we do Typo3 Updates (soon).
Good to know that the extension works under 7.6, haven’t tested this yet.
There is also a plan to support powermail 4.0.1, but I once looked into the code and saw that there are some issues, like you said.

Since the extension can also fill out pdf forms, i'm not sure if there are enough people needing this feature, so that it could be worth integration it into powermail.

You are very welcome to do an error report and a pull request.

**Comment by sypets** [comment]
Hello,
I don't think you'd have to change that much. I'm happy to report that it runs on a testsystem TYPO3 8.7.4 and the latest powermail 4.1.0 here (with the patch I submitted, because otherwise there will also be an error with double opt in). Of course I haven't been able to test everything yet. 

Once there are official 7.6 and 8.x versions, I can do some more testing. However, we will be upgrading our production systems to TYPO3 8 asap so I would rather focus on supporting that.

**Comment by typo3ua** [comment]
> Since the extension can also fill out pdf forms, i'm not sure if there are enough people needing this feature, so that it could be worth integration it into powermail.

I need this functions. Will they be available in new version?

**Comment by typo3ua** [comment]
> Integration of dynamic link: in email/PDF after online form completion a link to webid with a unique request id must be integrated - i will complete info about this in PDF MindMap asap.

Does "powermailpdf" do it?

**Comment by Starkmann** [comment]
@typo3ua We dont have a demo but here you can see the documentation
https://docs.typo3.org/typo3cms/extensions/powermailpdf/

**Comment by Starkmann** [comment]
There are new version out
1.4.4 for powermail 3 and 4
2.4.4 for powermail 5 and 6
Both are supporting typo3 7.6 and 8.7
